// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// ----------------------------------------------------------------------------
//
if ~win64() then
  warning(_("This module requires a Windows x64 platform."));
  return
end
//
trans_lib_path = get_absolute_file_path('loader.sce');
//
// ulink previous function with same name
[bOK, ilib] = c_link('trans_lib');
if bOK then
  ulink(ilib);
end
//
list_functions = [ 'transpose';
];
addinter(trans_lib_path + filesep() + 'trans_lib' + getdynlibext(), 'trans_lib', list_functions);
// remove temp. variables on stack
clear trans_lib_path;
clear bOK;
clear ilib;
clear list_functions;
// ----------------------------------------------------------------------------
